# Generated by Django 3.0.5 on 2020-04-24 17:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='welcome'),
            preserve_default=False,
        ),
    ]
