# Generated by Django 3.0.5 on 2020-04-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finder.Category'),
        ),
    ]
