# Generated by Django 3.0.5 on 2020-04-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_auto_20200426_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='feedbacks/%Y/%m/%d/'),
        ),
    ]
