# Generated by Django 3.0.5 on 2020-04-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_auto_20200426_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
