# Generated by Django 3.0.5 on 2020-04-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_auto_20200427_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'slug')},
        ),
    ]
