# Generated by Django 3.0.5 on 2020-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0015_auto_20200429_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
